config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :menu_items
  resources :reservations
  resources :orders
  resources :cart_items, only: [:index, :create, :destroy] do
    collection do
      post 'checkout'
    end
  end

  get '/', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/menu', to: 'pages#menu'
  get '/contact', to: 'pages#contact'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  after_create :addcartitem
  belongs_to :user
  belongs_to :menu_item
  belongs_to :order, optional: true

   private

    def addcartitem
        puts "item save into the addtocart"
    end
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
    has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, class_name: 'CartItem', foreign_key: :order_id
  has_many :cart_items
end

app/models/reservation.rb
class Reservation < ApplicationRecord

    validates :name, presence: true
    validates :email, presence: true
    validates :phone, presence: true
    validates :seats, presence: true
    validates :date, presence: true
    validates :time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :cart_items       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    
    def index
        @cart_item = current_user.cart_items.all
        @cart = calculate_total()
    end

    def create
        @cart_item = current_user.cart_items.build(menu_item_id: params[:menu_item_id])
        @cart_item.save
        redirect_to @cart_item, notice: 'Item added to cart'
    end

    def destroy
        @cart_item = current_user.cart_items.find(params[:id])
        @cart_item.destroy
        redirect_to cart_items_path, notice: 'Item removed from cart'
    end

    def checkout
        order = current_user.orders.create(total: calculate_total)
        current_user.cart_items.update_all(order_id: order.id,user_id: current_user.id)
        # current_user.cart_items.delete_all
        OrderConfirmationJob.perform_later(current_user)
        # toastr.success('Order successfully created!')
        redirect_to root_path, notice: 'Order placed successfully'
    end

    private

    def calculate_total 
        current_user.cart_items.sum { |item| item.menu_item.price * item.quantity=1 }
    end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

    def index
      @menu_items = MenuItem.all  
    end
    
    def show
      @menu_items = MenuItem.find(params[:id])
    end  
    
    def new 
      @menu_items = MenuItem.new
    end    

    def create
      @menu_items = MenuItem.new(menu_params)
      if @menu_items.save
        redirect_to @menu_items
      else
        render :new, status: :unprocessable_entity
      end
    end
    def edit
      @menu_items = MenuItem.find(params[:id])
    end
    
    def update
      @menu_items = MenuItem.find(params[:id])
      if @menu_items.update(menu_params)
        redirect_to @menu_items
      else
        render :edit, status: :unprocessable_entity
      end
    end
    def delete
    end
    
    private
    def menu_params
        params.require(:menu_item).permit(:name, :description, :price, :image)
    end 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    def index
        @orders = current_user.orders.includes(:cart_items)
    end    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def menu
    @menu_items = MenuItem.all
  end

  def contact
  end  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authenticate_user!, only: %i[create]

    def index
        @reservation = Reservation.all
    end
    
    def show 
        @reservation = Reservation.find(params[:id])
    end    
    def new
        @reservation = Reservation.new
    end
    
    def create
       @reservation = Reservation.new(reservation_params)
        if @reservation.save
          redirect_to @reservation, notice: 'Reservation successfully created.'
        else
          render :new
        end
    end

    def edit
        @reservation = Reservation.find(params[:id])
    end    

    def update
        @reservation = Reservation.find(params[:id])
        if @reservation.update(reservation_params)
            redirect_to @reservation
          else
            render :edit, status: :unprocessable_entity
          end
    end  
    
    def destroy
        @reservation = Reservation.find(params[:id])
        @reservation.destroy

        redirect_to new_reservation_path, status: :see_other
    end    
    
    private
    
    def reservation_params
        params.require(:reservation).permit(:name, :email, :phone, :seats, :date, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/cart_items/cart.html.erb
<h2>Your Cart</h2>
<div class="cart-items">
  <% current_user.cart_items.each do |item| %>
    <div class="cart-item">
  <%= item.menu_item.name %>
  Quantity: <%= form_with(model: item, url: cart_item_path(item), method: :patch) do |form| %>
    <%= form.number_field :quantity, min: 1 %>
    <%= form.submit 'Update' %>
  <% end %>
  <%= link_to 'Remove', cart_item_path(item), method: :delete %>
</div>
  <% end %>
  <p>Total: $<%= calculate_total %></p>
  <%= link_to 'Checkout', checkout_cart_items_path, class: 'btn btn-primary' %>
</div>

app/views/cart_items/checkout.html.erb
<h1>Checkout</h1>
<p>Total: <%= calculate_total %></p>
<%= link_to 'Place Order', orders_path, method: :post, class: 'btn btn-success' %>

 <%= form_with(url: cart_items_path, method: :post) do |form| %>
      <%= form.hidden_field :menu_item_id, value: item.id %>
      <%= form.submit 'Add to Cart' %>
      <% end %>

app/views/cart_items/index.html.erb
<div class="add-cart">
<h1>Your Cart</h1>
<div class="cart-items">
<% current_user.cart_items.each do |cart_item| %>
  <div class="cart-item">
  <%= image_tag(cart_item.menu_item.image, class: 'cart-img') %>
    <p><%= cart_item.menu_item.name %></p>
    <p>$<%= cart_item.menu_item.price %></p>
   Quantity: 1
   
    
   
    <%= link_to cart_item_path(cart_item), class: 'btn-rem', data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } do %>
  <i class="fa-solid fa-trash"></i> 
<% end %>
              
  </div>
<% end %>
</div>
<p>Total: <%= @cart%></p>
 <%= link_to 'Checkout', checkout_cart_items_path, class: 'btn btn-primary',data: {
                    turbo_method: :post,
                    turbo_confirm: "Are you sure?"
                  } %> 

</div>                  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   
  
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" 
    integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" 
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </head>

  <body>


    <%= yield %>
  </body>
</html>

app/views/menu_items/_form.html.erb
<h2>Create a Menu</h2>
<%= form_with(model: menuitems) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_field :description %>

  <%= form.label :price %>
  <%= form.text_field :price %>

   <%= form.label :image %>
   <%= form.file_field :image %>

  <%= form.submit "Create Menu" %>
<% end %>

app/views/menu_items/edit.html.erb
<%= render "form", menuitems: @menu_items%>

app/views/menu_items/index.html.erb
<h2>Menu</h2>
<div class="menu-items">
  <% @menu_items.each do |item| %>
    <div class="menu-item">
      <%= image_tag(item.image) %>
      <h3><%= item.name %></h3>
      <p><%= item.description %></p>
      <p>$<%= item.price %></p>
    </div>
  <% end %>
</div>

app/views/menu_items/new.html.erb
<%= render "form", menuitems: @menu_items%>

app/views/menu_items/show.html.erb
<h2>Menu</h2>
<div class="menu-items">
 
    <div class="menu-item">
      <%= image_tag(@menu_items.image) %>
      <h3><%= @menu_items.name %></h3>
      <p><%= @menu_items.description %></p>
      <p>$<%= @menu_items.price %></p> 
    </div>
 
</div>

app/views/orders/index.html.erb
<div class="orders">
<% @orders.each do |order| %>
  <h2>Order: <%= order.id %></h2>
    <div class="order-items">
    <% order.cart_items.each do |item| %>
      <div class="order-item">  
      <%= image_tag(item.menu_item.image) %>  
      <h2><%= item.menu_item.name %></h2> 
      <p><%= item.menu_item.price %></p>
    <% end %>
 
  <h1>Total: <%= order.total %></h1>
<% end %>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark ">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">SS Restaurant</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About us</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="/menu">Menu</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="/contact">Contact</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Reservation', new_reservation_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
       
       
          <%= link_to "#{content_tag(:i, '', class: 'fa-solid fa-cart-shopping')}".html_safe,
            cart_items_path,
            class: 'nav-link' %>

          
        </li>
        
        <% if user_signed_in? %>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-button' %>
        <% else %>
          <%= button_to "Sign in", new_user_session_path, class: 'nav-button' %>
        <% end %>     
        
        
      </ul>
     
    </div>
  </div>
</nav>

app/views/pages/about.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="index.css">
    <title>Hello, world!</title>
  </head>
  <body>
   <%= render "navbar"%>

   <section class="about">
     <h1>Welcome to SS Restaurant</h1>  
     <p>Where every ingredient tells a story</p> 
     <button class="home-button">Our Menu</button>
   </section> 







    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" 
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" 
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" 
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" 
    crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/contact.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="index.css">
    <title>Hello, world!</title>
  </head>
  <body>
   <%= render "navbar"%>

   <section class="contact">
     <p>Where every ingredient tells a story</p> 
     <button>Our Menu</button>
   </section> 

  







    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" 
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" 
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" 
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" 
    crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="index.css">
    <title>Hello, world!</title>
  </head>
  <body>
   <%= render "navbar"%>

   <section class="home">
     <h1>Welcome to SS Restaurant</h1>  
     <p>Where every ingredient tells a story</p> 
     <button class="home-button"><a href="/menu">Our Menu</a></button>
   </section> 







    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" 
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" 
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" 
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" 
    crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/menu.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="index.css">
    <title>Hello, world!</title>
  </head>
  <body>
   <%= render "navbar"%>

   <section class="menu">
     <h1>Where every ingredient tells a story</h1> 
     <button class="home-button">Our Menu</button>
   </section> 

   <div class="our-menu"> 
   <h1>Our Menu</h1>
    <div class="menu-items">
    <% @menu_items.each do |item| %>
    <div class="menu-item" data-item-id="<%= item.id %>" >
      <%= image_tag(item.image) %>
      <h3><%= item.name %></h3>
      <p><%= item.description %></p>
   
      <p>$<%= item.price %></p>
      <%= form_with(url: cart_items_path, method: :post) do |form| %>
      <%= form.hidden_field :menu_item_id, value: item.id %>
      <%= form.submit 'Add to Cart' %>
      <% end %>
       <%# <button class="add-to-cart-button">Add to Cart</button> %>
     
      

    </div>
    <% end %>
    </div>
    </div>







    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" 
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" 
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" 
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" 
    crossorigin="anonymous"></script>
    <script>
    $(document).ready(function() {
      var csrfToken = document.querySelector("meta[name='csrf-token']").getAttribute("content");
    $('.add-to-cart-button').click(function() {
        var itemId = $(this).closest('.menu-item').data('item-id');
       var requestData = {
    menu_item_id: itemId  // Your data goes here
};
        $.ajax({
            url: '/cart_items',
            method: 'POST',
            dataType: 'json',
    contentType: 'application/json',
    headers: {
        'X-CSRF-Token': csrfToken,
    },
    data: JSON.stringify(requestData), 
            success: function(response) {
                alert("Item successfully added to your cart")
            },
            error: function(xhr, status, error) {
                console.log(error);
            }
        });
    });
});

    </script>
  </body>
</html>

app/views/reservations/_form.html.erb
 <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="index.css">
    <title>Hello, world!</title>
  </head>
  <body>
    <%= render "pages/navbar"%>
<div class="reservation">
<div class="reserve">
<h2>Reservation</h2>
<%= form_with(model: reservation) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :phone %>
  <%= form.text_field :phone %>

  <%= form.label :seats %>
  <%= form.number_field :seats %>

  <%= form.label :date %>
  <%= form.date_field :date %>

  <%= form.label :time %>
  <%= form.time_field :time %>

  <%= form.submit " Reservation" %>
<% end %>
</div>
</div>









    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" 
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" 
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" 
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" 
    crossorigin="anonymous"></script>
  </body>
</html>


 

app/views/reservations/edit.html.erb
<%= render "form", reservation: @reservation%>

app/views/reservations/index.html.erb
<h2>Reservations</h2>
<div class="reservations">
  <% @reservation.each do |res| %>
    <div class="r">
      <h2><%= res.name %></h2>
      <p><%= res.email %></p>
      <p><%= res.phone %></p>
      <p><%= res.seats %></p>
      <p><%= res.date %></p>
      <p><%= res.time %></p>
    </div>
  <% end %>
</div>

app/views/reservations/new.html.erb
<%= render "form", reservation: @reservation%>

app/views/reservations/show.html.erb
<h1>Reservation</h1>
<h2><%= @reservation.name %></h2>
    <p><%= @reservation.email %></p>
    <p><%= @reservation.phone %></p>
    <p><%= @reservation.seats %></p>
    <p><%= @reservation.date %></p>
    <p><%= @reservation.time %></p>
     <%= link_to 'Edit Reservation', edit_reservation_path %>
     <li><%= link_to "Delete Reservation", reservation_path(@reservation), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>